spring:
  application:
    name: sse-mcp-server

  ai:
    mcp:
      server:
        enabled: true
        stdio: false
        name: sse-mcp-server
        version: 1.0.0
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        sse-endpoint: /api/v1/sse
        sse-message-endpoint: /api/v1/mcp
        type: sync
        capabilities:
          completion: true
          prompt: true
          resource: true
          tool: true

  datasource:
    url: jdbc:mariadb://localhost:3306/netis
    username: root
    password: ntflow
    driver-class-name: org.mariadb.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.ssemcpserver.model
    configuration:
      map-underscore-to-camel-case: true

logging:
  level:
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE
    org.mybatis: DEBUG
    com.example.ssemcpserver: DEBUG
    org.mybatis: DEBUG
    com.example.ssemcpserver: DEBUG
    org.mybatis: DEBUG
    com.example.ssemcpserver: DEBUG